# permissions for end users to view appresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appresource-viewer-role
rules:
- apiGroups:
  - cloudship.toucansoft.io
  resources:
  - appresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudship.toucansoft.io
  resources:
  - appresources/status
  verbs:
  - get
