# permissions for end users to view resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appresource-viewer-role
rules:
  - apiGroups:
      - cloudship.toucansoft.io
    resources:
      - resources
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - cloudship.toucansoft.io
    resources:
      - resources/status
    verbs:
      - get
