# permissions for end users to edit resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appresource-editor-role
rules:
  - apiGroups:
      - cloudship.toucansoft.io
    resources:
      - resources
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cloudship.toucansoft.io
    resources:
      - resources/status
    verbs:
      - get
