
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cloudship.toucansoft.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudship.toucansoft.io
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudship.toucansoft.io
  resources:
  - appresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudship.toucansoft.io
  resources:
  - appresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cloudship.toucansoft.io
  resources:
  - appservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudship.toucansoft.io
  resources:
  - appservices/status
  verbs:
  - get
  - patch
  - update
