# permissions for end users to edit services.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appservice-editor-role
rules:
  - apiGroups:
      - cloudship.toucansoft.io
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cloudship.toucansoft.io
    resources:
      - services/status
    verbs:
      - get
