# permissions for end users to view services.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appservice-viewer-role
rules:
  - apiGroups:
      - cloudship.toucansoft.io
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - cloudship.toucansoft.io
    resources:
      - services/status
    verbs:
      - get
