apiVersion: cloudship.toucansoft.io/v1alpha1
kind: AppService
metadata:
  name: nginx
spec:
  containers:
    - name: foo
      image: nginx
      ports:
        - name: http
          portNumber: 80
