## Append samples you want in your CSV to this file as resources ##
resources:
- cloudship_v1alpha1_application.yaml
- cloudship_v1alpha1_appservice.yaml
- cloudship_v1alpha1_appresource.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
